### ISSUE TITLE
I can't open the application. 

### ISSUE THREAD

**Issue by ibaris** [edipox/wunderlistux#28]
If I try to start the application, nothing happens (Ubuntu 18.10). There is also no error message. Nothing happens. I tried to install it with the `install-script.sh` too. It prints that everything went well.

Any suggestions?

**Comment by nikartz** [comment]
I experience the same problem. Also installed by using`install-script.sh` without any errors.

**Comment by edipox** [comment]
Hi guys, I was able to replicate the issue. 
Let me share what I tried
``` 
sudo ./bin/install.sh
``` 
the app doesn't open, I checked the output of
``` 
/opt/wunderlistux/Wunderlistux
``` 
and saw that some libs are missing
``` 
/opt/wunderlistux/Wunderlistux: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
``` 
so it looks like we have ` libgconf-2-4`  as a missing dependency.
I also tried downloading and installing the deb package
``` 
sudo dpkg -i ~/Downloads/Wunderlistux_0.0.8_amd64.deb
``` 
and got the same error. So finally I run 
```
sudo apt --fix-broken install
``` 
that fixed the missing dependencies and the app worked.
so that's somehow the workaround for now, you can also try installing ` libgconf-2-4`  before running the install script, but I haven't tried that.

**Comment by edipox** [comment]
Updated the [deb file for Linux (x64)](https://github.com/edipox/wunderlistux/releases/download/v0.0.9-linux-x64/Wunderlistux_1.6.2_amd64.deb), the [install script](https://github.com/edipox/wunderlistux/releases/download/v0.0.9-linux-x64/install.sh), as well as the [AppImage](https://github.com/edipox/wunderlistux/releases/download/v0.0.9-linux-x64/Wunderlistux-1.6.2.AppImage). So if you try the new [install script](https://github.com/edipox/wunderlistux/releases/download/v0.0.9-linux-x64/install.sh) it should work now :crossed_fingers:

**Comment by ibaris** [comment]
Great! Thank you for your efforts. Now it works :+1: :blush:
